# Generated by Django 5.1.1 on 2024-11-09 20:44

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField()),
                ('preferredColor', models.IntegerField()),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[256, 256], upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campusID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PairType',
            fields=[
                ('pairTypeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('name_short', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('priority', models.IntegerField()),
                ('isAdmin', models.BooleanField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Authorize',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('email', models.TextField()),
                ('password_hash', models.TextField()),
                ('session_token', models.TextField(default='<function uuid4 at 0x000002D11C41D940>', editable=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('auditoryID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('campus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='application.campus')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='application.group'),
        ),
        migrations.CreateModel(
            name='QueueList',
            fields=[
                ('queueID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('write_mode', models.IntegerField()),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.group')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('orderStatus', models.BooleanField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.user')),
                ('queue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.queuelist')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.TextField()),
                ('state', models.IntegerField()),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.group')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.subject')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='application.userrole'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('pairNumber', models.IntegerField()),
                ('auditory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.auditory')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.group')),
                ('pairType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='application.pairtype')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.subject')),
            ],
            options={
                'unique_together': {('week', 'weekday', 'pairNumber', 'group')},
            },
        ),
    ]
