# Generated by Django 5.1.1 on 2024-11-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorize',
            name='session_token',
            field=models.TextField(default='<function uuid4 at 0x000001928B75D940>', editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, on_delete=models.SET(0), to='application.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='application.userrole'),
        ),
    ]
