# Generated by Django 5.1.1 on 2024-11-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_authorize_session_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferredColor',
            new_name='preferredTheme',
        ),
    ]
