# Generated by Django 5.1.1 on 2024-11-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelist',
            name='title',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.group'),
        ),
    ]
