# Generated by Django 5.1.1 on 2024-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_queue_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
