# Generated by Django 5.1.1 on 2024-11-16 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_queuelist_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='token',
            field=models.TextField(default=uuid.uuid4, editable=False),
        ),
    ]
