# Generated by Django 5.1.1 on 2024-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_queue_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorize',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorize',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
